[package]
name = "unit3d-announce"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.0", default-features = true, features = ["std"] }
axum = { version = "0.7.5", default-features = false, features = ["http1", "tokio", "query", "macros", "json"] }
chrono = { version = "0.4.22", default-features = false, features = ["serde"] }
dotenvy = { version = "0.15.0", default-features = false }
indexmap = { version = "2.0.0", default-features = false, features = ["std", "serde"] }
memchr = { version = "2.6.0", default-features = false, features = ["std"] }
parking_lot = "0.12.1"
rand = { version = "0.8.5", default-features = false, features = ["alloc", "small_rng"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_bytes = "0.11.14"
serde_repr = { version = "0.1", default-features = false }
sqlx = { version = "0.8.0", default-features = false, features = ["runtime-tokio-rustls", "macros", "mysql", "chrono", "ipnetwork"] }
thiserror = { version = "2.0.0", default-features = false }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "signal", "sync"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
